// <auto-generated />
using System;
using Backend_DispenXCore.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_DispenXCore.Api.Migrations
{
    [DbContext(typeof(DispenXDbContext))]
    [Migration("20260608065257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend_DispenXCore.Api.src.AlertasStock.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContenedorId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Enviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grano")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("PorcentajeActual")
                        .HasColumnType("double");

                    b.Property<double>("UmbralDisparo")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("alertas", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Dispensadores.Domain.Entities.Dispensator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("dispensators", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Dispensadores.Domain.Entities.DispensatorStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("int");

                    b.Property<int>("DailyTotal")
                        .HasColumnType("int");

                    b.Property<int>("DispensatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextDispenseAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DispensatorStatuses");
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Dispensadores.Domain.Entities.DispenserEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmountDispensed")
                        .HasColumnType("int");

                    b.Property<int>("DispensatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DispensedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplyType")
                        .HasColumnType("int");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DispenserEvents");
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Dispensadores.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("DispensatorId")
                        .HasColumnType("int");

                    b.Property<string>("FrequencyDays")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FrequencyDays");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ScheduledTime")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("SmartRefill")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SupplyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Dispositivos.Domain.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Dispositivos.Domain.Entities.Firmware", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Changelog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("firmwares", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.IAM.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Inventario.Domain.Entities.Contenedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("NivelActual")
                        .HasColumnType("double");

                    b.Property<double>("PesoActual")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("contenedores", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Inventario.Domain.Entities.DatoSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContenedorId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Flujo")
                        .HasColumnType("double");

                    b.Property<double>("Nivel")
                        .HasColumnType("double");

                    b.Property<double>("Peso")
                        .HasColumnType("double");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("datos_sensor", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.NotificacionesUsuario.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Unread")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Usuarios.Domain.Entities.Dispensador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("dispensadores", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Usuarios.Domain.Entities.PerfilUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DispensadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DispensadorId");

                    b.ToTable("perfiles_usuarios", (string)null);
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Inventario.Domain.Entities.Contenedor", b =>
                {
                    b.OwnsOne("Backend_DispenXCore.Api.src.Inventario.Domain.ValueObjects.Capacidad", "CapacidadMaxima", b1 =>
                        {
                            b1.Property<Guid>("ContenedorId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("CapacidadMaxima_Unidad");

                            b1.Property<double>("Valor")
                                .HasColumnType("double")
                                .HasColumnName("CapacidadMaxima_Valor");

                            b1.HasKey("ContenedorId");

                            b1.ToTable("contenedores");

                            b1.WithOwner()
                                .HasForeignKey("ContenedorId");
                        });

                    b.OwnsOne("Backend_DispenXCore.Api.src.Inventario.Domain.ValueObjects.TipoGrano", "Grano", b1 =>
                        {
                            b1.Property<Guid>("ContenedorId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Grano");

                            b1.HasKey("ContenedorId");

                            b1.ToTable("contenedores");

                            b1.WithOwner()
                                .HasForeignKey("ContenedorId");
                        });

                    b.Navigation("CapacidadMaxima")
                        .IsRequired();

                    b.Navigation("Grano")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Usuarios.Domain.Entities.PerfilUsuario", b =>
                {
                    b.HasOne("Backend_DispenXCore.Api.src.Usuarios.Domain.Entities.Dispensador", "Dispensador")
                        .WithMany("Perfiles")
                        .HasForeignKey("DispensadorId");

                    b.Navigation("Dispensador");
                });

            modelBuilder.Entity("Backend_DispenXCore.Api.src.Usuarios.Domain.Entities.Dispensador", b =>
                {
                    b.Navigation("Perfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
